
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh syed-cicd --zone=europe-west2-c --command='/bin/sh /home/syedmohammedibrahim_sd/pull.sh'
